// DTOs for Super Admin API

// User Management
export interface UserInfoDto {
  id: number
  username: string
  email: string
  roles: Set<string>
  isActive: boolean
  organizationId?: string // Assuming organizationId might be part of UserInfoDto based on usage
  organizationName?: string // Organization name for UI display
}

export interface UserUpdateDto {
  username?: string
  email?: string
}

export interface UserPasswordResetDto {
  newPassword: string
}

// Bulk User Operations
export interface BulkUserOrganizationDto {
  userIds: number[]
  organizationId: string
}

export interface BulkUserRoleDto {
  userIds: number[]
  roleName: string
}

export interface BulkUserIdsDto {
  userIds: number[]
}

// Role Management
export interface RoleDto {
  id?: number // id is generated by backend, so optional on create
  name: string
}

// Organization Management
export interface OrganizationDto {
  id?: string // id is generated by backend, so optional on create
  name: string
}

// Admin Audit Log
export interface AdminAuditLogDto {
  id: number
  adminUsername: string
  actionType: string
  targetEntityType: string
  targetEntityId: string
  details: string
  timestamp: string // ISO DateTime String
}

// System Settings
export interface SystemSettingDto {
  settingKey: string
  settingValue: string
}
