/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/access-logs': RouteRecordInfo<'/access-logs', '/access-logs', Record<never, never>, Record<never, never>>,
    '/collaborative-editing': RouteRecordInfo<'/collaborative-editing', '/collaborative-editing', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/email-notifications': RouteRecordInfo<'/email-notifications', '/email-notifications', Record<never, never>, Record<never, never>>,
    '/expiring-links': RouteRecordInfo<'/expiring-links', '/expiring-links', Record<never, never>, Record<never, never>>,
    '/folder-explorer': RouteRecordInfo<'/folder-explorer', '/folder-explorer', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/maintenance': RouteRecordInfo<'/maintenance', '/maintenance', Record<never, never>, Record<never, never>>,
    '/multi-tenant-sharing': RouteRecordInfo<'/multi-tenant-sharing', '/multi-tenant-sharing', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/password-downloads': RouteRecordInfo<'/password-downloads', '/password-downloads', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/qr-code-generation': RouteRecordInfo<'/qr-code-generation', '/qr-code-generation', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/secure-uploads': RouteRecordInfo<'/secure-uploads', '/secure-uploads', Record<never, never>, Record<never, never>>,
    '/superadmin/AuditLogViewer': RouteRecordInfo<'/superadmin/AuditLogViewer', '/superadmin/AuditLogViewer', Record<never, never>, Record<never, never>>,
    '/superadmin/OrganizationManagement': RouteRecordInfo<'/superadmin/OrganizationManagement', '/superadmin/OrganizationManagement', Record<never, never>, Record<never, never>>,
    '/superadmin/RoleManagement': RouteRecordInfo<'/superadmin/RoleManagement', '/superadmin/RoleManagement', Record<never, never>, Record<never, never>>,
    '/superadmin/SuperAdminDashboard': RouteRecordInfo<'/superadmin/SuperAdminDashboard', '/superadmin/SuperAdminDashboard', Record<never, never>, Record<never, never>>,
    '/superadmin/SystemSettings': RouteRecordInfo<'/superadmin/SystemSettings', '/superadmin/SystemSettings', Record<never, never>, Record<never, never>>,
    '/superadmin/UserManagement': RouteRecordInfo<'/superadmin/UserManagement', '/superadmin/UserManagement', Record<never, never>, Record<never, never>>,
    '/verify-email': RouteRecordInfo<'/verify-email', '/verify-email', Record<never, never>, Record<never, never>>,
  }
}
